'''
This will apply noise to DNS grid, avoiding the whole interp -> uninterp process

Using 2nd Order Finite Difference Scheme on the DNS Grid, matching Callaham et al. (2021)

NOTE: Users must specify the desired save location using save_dir string. 
Adjusting the no_trials is essential as well to not consume excess storage, which is not necessary unless running a large ensemble to get a statistical description of the performance of the method.
'''
import matplotlib.pyplot as plt
import numpy as np
from numpy.random import randint
import sklearn as sk
from sklearn.mixture import GaussianMixture # jaxxx??? # Hyakkk
from sklearn.decomposition import SparsePCA
from scipy.io import loadmat
import h5py
from scipy import sparse, linalg
from scipy.optimize import curve_fit, root
from scipy.integrate import odeint
from scipy.interpolate import interp1d
#from scipy.signal import convolve2d, fftconvolve # check jax
import os
# os.environ['XLA_PYTHON_CLIENT_PREALLOCATE'] = 'false'

from jax.scipy.signal import fftconvolve
import math
import time

import pickle

import matplotlib as mpl
from matplotlib.colors import ListedColormap

import jax
jax.config.update("jax_enable_x64", True)
from jax import numpy as jnp
from jax import jit ,vmap
from jax.scipy.integrate import trapezoid as jtrap

# Seaborn colormap
import seaborn as sns
sns_list = sns.color_palette('deep').as_hex()
sns_list.insert(0, '#ffffff')  # Insert white at zero position

sns_cmap = ListedColormap(sns_list)
cm = sns_cmap


mpl_colors = ['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728',
            '#9467bd', '#8c564b', '#e377c2', '#7f7f7f',
            '#bcbd22', '#17becf']


from scipy.interpolate import griddata

# export XLA_PYTHON_CLIENT_PREALLOCATE=false
# os.environ['XLA_PYTHON_CLIENT_PREALLOCATE'] = 'false'

def get_JH_DNS_BL_Data(flatten_protocol = 'C'):#x_min, x_max, y_min, y_max, noisy=False, noise_pct=0.0, Nx=0,Ny=0
    file = h5py.File('../data/Transition_BL_Time_Averaged_Profiles.h5', 'r')

    x_JH_DNS = jnp.array(file['x_coor'])
    y_JH_DNS = jnp.array(file['y_coor'])
    # flatten data fields
    u = jnp.array(file['um']).flatten(flatten_protocol)
    v = jnp.array(file['vm']).flatten(flatten_protocol)
    p = jnp.array(file['pm']).flatten(flatten_protocol)
    Ruu = (jnp.array(file['uum'])).flatten(flatten_protocol) - u**2
    Ruv = (jnp.array(file['uvm'])).flatten(flatten_protocol) - u*v
    # Rvv = (jnp.array(file['uvm'])).flatten() - v**2

    data = [u,v,p,Ruu,Ruv]

    return data,x_JH_DNS,y_JH_DNS

def train_gmm_model(nc, features, sample_pct=0.1, mode='kmeans'):
    seed = randint(2**32)
    # print(seed)
    model = GaussianMixture(n_components=nc, random_state=seed, init_params=mode)

    # PERMUTATION
    mask = np.random.permutation(features.shape[0])[:int(sample_pct*features.shape[0])]
    model.fit(features[mask, :])

    return model

def train_sPCA_model(alpha_opt, features, nfeatures, nc, cluster_idx):
    labels = [r'$\bar{u} \bar{u}_x$', r'$\bar{v}\bar{u}_y$',
        r'$\nu \nabla \bar{\bf{u}}$', r'$\rho^{-1} \bar{p}_x$', 
        r'$\overline{({u^\prime} ^2)}_x$', r'$\overline{(u^\prime v^\prime)}_y$']
    spca_model = np.zeros([nc, nfeatures])
    for i in range(nc):
        feature_idx = np.nonzero(cluster_idx==i)[0]
        cluster_features = features[feature_idx, :]
        spca = SparsePCA(n_components=1, alpha=alpha_opt)
        spca.fit(cluster_features)
        # print('GMM Cluster {0}:'.format(i))
        active_terms = np.nonzero(spca.components_[0])[0]
        if len(active_terms)>0:
            # print([labels[k] for k in active_terms])
            spca_model[i, active_terms] = 1  # Set to 1 for active terms in model
        else: print('None')

    return spca_model

def interpolateBLDataForFFTConvolve(data, X_interp, Y_interp, xy, noise_std=0.0):
    # Interpolate data
    if noise_std > 0.0:
        data_interp = griddata(xy, data, (X_interp, Y_interp), method='cubic') + np.random.normal(scale=noise_std, size=X_interp.shape)#.flatten()#np.zeros(X_interp.shape)
    else:
        data_interp = griddata(xy, data, (X_interp, Y_interp), method='cubic')

    return data_interp

def interpolateWeakFieldsOntoJH_DNS_Grid(X_JH_DNS,Y_JH_DNS,data_weak,idx_support_bound_x,idx_support_bound_y,x_centers,y_centers):
    # truncate the data which is generated by TFs with partial
    data_weak_JH_DNS =  griddata(
                            np.vstack([x_centers.flatten(),
                                        y_centers.flatten()]).T,
                                        data_weak.flatten(),
                                        (X_JH_DNS[idx_support_bound_y:-idx_support_bound_y, idx_support_bound_x:-idx_support_bound_x],
                                        Y_JH_DNS[idx_support_bound_y:-idx_support_bound_y, idx_support_bound_x:-idx_support_bound_x]),
                                'nearest')
    return data_weak_JH_DNS


def main():
    # noises = np.array([0.01, 0.025, 0.05, 0.0])
    #np.array([0.1, 0.25, 0.5, 1.0])
    
    # noises = np.array([0.02])
    noises = np.array([0.03])
    # noises = np.array([0.04])

    # Import data
    data, x, y = get_JH_DNS_BL_Data(flatten_protocol='F')

    # Assemble Derivatives operator
    if True:
        dx = float(x[1]-x[0])
        dy = np.array(y[1:]-y[:-1])

        nx = len(x)
        ny = len(y)

        Dy = sparse.diags( [-1, 1], [-1, 1], shape=(ny, ny) ).toarray()
        # Second-order forward/backwards at boundaries
        Dy[0, :3] = np.array([-3, 4, -1])
        Dy[-1, -3:] = np.array([1, -4, 3])
        for j in range(ny-1):
            Dy[j, :] = Dy[j, :]/(2*dy[j])
        Dy[-1, :] = Dy[-1, :]/(2*dy[-1])

        # Repeat for each x-location
        Dy = sparse.block_diag([Dy for j in range(nx)])

        Dx = sparse.diags( [-1, 1], [-ny, ny], shape=(nx*ny, nx*ny))
        Dx = sparse.lil_matrix(Dx)
        # Second-order forwards/backwards at boundaries
        for j in range(ny):
            Dx[j, j] = -3
            Dx[j, ny+j] = 4
            Dx[j, 2*ny+j] = -1
            Dx[-(j+1), -(j+1)] = 3
            Dx[-(j+1), -(ny+j+1)] = -4
            Dx[-(j+1), -(2*ny+j+1)] = 1
        Dx = Dx/(2*dx)

        Dx = sparse.csr_matrix(Dx)
        Dy = sparse.csr_matrix(Dy)

        Dxx = 2*(Dx @ Dx)
        Dyy = 2*(Dy @ Dy)

    labels = [r'$\bar{u} \bar{u}_x$', r'$\bar{v}\bar{u}_y$',
        r'$\nu \nabla \bar{\bf{u}}$', r'$\rho^{-1} \bar{p}_x$', 
        r'$\overline{({u^\prime} ^2)}_x$', r'$\overline{(u^\prime v^\prime)}_y$']
    for noise in noises:
        #noise = 0.0 #as a percentage of the std of the V-velocity data

        no_runs = 100
        nfeatures = 6
        nc = 6

        save_dir = 'plots/2ndOrderFD_Derivatives_On_DNS_Grid/'
        # os.mkdir(save_dir)
        os.mkdir(save_dir + f'{noise}_Noise/')

        plot_terms = False

        for i in range(no_runs):
            # Import data fresh every new instance
            data, x, y = get_JH_DNS_BL_Data(flatten_protocol='F')
            X, Y = np.meshgrid(x,y)
            xy = np.vstack([X.flatten('F'),Y.flatten('F')]).T

            x0 = 30.5
            xF = 999.7
            y0 = 0.01
            yF = 26.45
            grid_spacing = 0.01

            x_range = np.arange(x0,xF,grid_spacing)
            y_range = np.arange(y0,yF,grid_spacing)

            X_interp, Y_interp = np.meshgrid(x_range, y_range)
            
            # add noise vector somewhere
            noise_std = noise * np.std(data[1])
            for j, field in enumerate(data):
                data[j] += np.random.normal(scale=noise_std, size=data[j].shape)

            # params for data
            U_inf = 1
            nu = 1/800

            nx = x_range.size
            ny = y_range.size

            x_for_derivatives = jnp.array(X[0,:])
            y_for_derivatives = jnp.array(Y[:,0])

            u = data[0]
            v = data[1]
            p = data[2]
            Ruu = data[3]
            Ruv = data[4]

            t0 = time.time()

            ux = Dx @ u
            uy = Dy @ u
            # vx = Dx @ v
            # vy = Dy @ v
            px = Dx @ p
            # py = Dy @ p
            lap_u = (Dxx + Dyy) @ u
            Ruux = Dx @ Ruu
            Ruvy = Dy @ Ruv

            UUx = (u * ux).reshape(X.shape, order='F')
            VUy = (v * uy).reshape(X.shape, order='F')
            nu_lap_u = (nu * lap_u).reshape(X.shape, order='F')
            Px = (px).reshape(X.shape, order='F')
            Ruu_x = (Ruux).reshape(X.shape, order='F')
            Ruv_y = (Ruvy).reshape(X.shape, order='F')

            
            nu = 1/800
            features = 1e3 * np.vstack([(UUx).flatten('F'),
                                (VUy).flatten('F'),
                                (nu_lap_u).flatten('F'),
                                (Px).flatten('F'),
                                (Ruu_x).flatten('F'),
                                (Ruv_y).flatten('F')]).T

            model = train_gmm_model(nc, features)

            nc_arr = np.array([6])

            for nc in nc_arr:
                os.mkdir(save_dir + f'{noise}_Noise/trial{i}/')

                model = train_gmm_model(nc, features)

                cluster_idx = model.predict(features)+1
                cluster_map = np.reshape(cluster_idx, (X).shape, order='F')
                # print('plotting')

                plt.figure(figsize = (15,4))
                plt.pcolormesh(X,
                               Y,
                               cluster_map, cmap = cm, vmin=-0.5, vmax=cm.N-0.5)
                plt.colorbar(boundaries=np.arange(0.5, int(nfeatures)+1.5), ticks=np.arange(1, int(nfeatures)+2))
                plt.savefig(save_dir + f'{noise}_Noise/trial{i}/ClusterDomain,nc{nc}')
                plt.close()

                X_JH_DNS_trunc = X
                Y_JH_DNS_trunc = Y

                C_list = []
                plt.figure(figsize=(9, 11))
                for j in range(nc):
                    plt.subplot(3, 3, j+1)
                    # get CVs
                    jth_cluster = (cluster_idx == j+1)
                    cluster_mask = np.array([k for k, x in enumerate(jth_cluster) if x])
                    C = np.cov(features[cluster_mask].T)
                    C_list.append(C)
                    plt.pcolor(C, vmin=-max(abs(C.flatten())), vmax=max(abs(C.flatten())), cmap='RdBu')
                    plt.gca().set_xticks(np.arange(0.5, nfeatures+0.5))
                    plt.gca().set_xticklabels(labels, fontsize=8)
                    plt.gca().set_yticks(np.arange(0.5, nfeatures+0.5))
                    plt.gca().set_yticklabels(labels, fontsize=8)
                    plt.gca().set_title('Cluster {0}'.format(j+1), fontsize=14)
                    
                plt.subplots_adjust(left=None, bottom=None, right=None, top=None, wspace=0.3, hspace=0.3)
                plt.suptitle("CV of CFD Data in Ensembled Clusters")
                plt.savefig(save_dir + f'{noise}_Noise/trial{i}/DataCV,nc{nc}')
                plt.close()

                # optimal_alpha = 10.0 # From Jared's paper, may be subject to change with noise tho...

                np.save(save_dir + f'{noise}_Noise/trial{i}/cluster_idx.npy', cluster_idx)
                np.save(save_dir + f'{noise}_Noise/trial{i}/features.npy', features)



            if plot_terms:
                plot_terms = False # Turn to false so we only plot the terms once.
                os.mkdir(save_dir + f'{noise}_Noise/features')

                X_JH_DNS_trunc = X
                Y_JH_DNS_trunc = Y

                plt.figure(figsize=(15, 3))
                plt.title('UUx')
                plt.pcolormesh(X_JH_DNS_trunc, Y_JH_DNS_trunc,UUx)
                plt.colorbar()
                plt.savefig(save_dir + f'{noise}_Noise/features/UU_x.png')
                plt.close()

                plt.figure(figsize=(15, 3))
                plt.title('VUy')
                plt.pcolormesh(X_JH_DNS_trunc, Y_JH_DNS_trunc,VUy)
                plt.colorbar()
                plt.savefig(save_dir + f'{noise}_Noise/features/VU_y.png')
                plt.close()

                plt.figure(figsize=(15, 3))
                plt.title('nu_LapU')
                plt.pcolormesh(X_JH_DNS_trunc, Y_JH_DNS_trunc,nu_lap_u)
                plt.colorbar()
                plt.savefig(save_dir + f'{noise}_Noise/features/nu_LapU.png')
                plt.close()

                plt.figure(figsize=(15, 3))
                plt.title('P_x')
                plt.pcolormesh(X_JH_DNS_trunc, Y_JH_DNS_trunc,Px)
                plt.colorbar()
                plt.savefig(save_dir + f'{noise}_Noise/features/P_x.png')
                plt.close()

                plt.figure(figsize=(15, 3))
                plt.title('Ruu_x')
                plt.pcolormesh(X_JH_DNS_trunc, Y_JH_DNS_trunc,Ruu_x)
                plt.colorbar()
                plt.savefig(save_dir + f'{noise}_Noise/features/Ruu_x.png')
                plt.close()

                plt.figure(figsize=(15, 3))
                plt.title('Ruv_y')
                plt.pcolormesh(X_JH_DNS_trunc, Y_JH_DNS_trunc,Ruv_y)
                plt.colorbar()
                plt.savefig(save_dir + f'{noise}_Noise/features/Ruv_y.png')
                plt.close()


if __name__ == "__main__":
    main()